apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: steveslokadev-tls
  namespace: projectcontour-roots
spec:
  # acme:
  #   config:
  #   - dns01:
  #       provider: route53
  #     domains:
  #     - '*.demo.projectcontour.io'
  #     - demo.projectcontour.io
  commonName: stevesloka.dev
  dnsNames:
  - stevesloka.dev
  issuerRef:
    name: letsencrypt-prod-dns
  secretName: steveslokadev-tls