apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: steveslokadev-tls
  namespace: root-proxies
spec:
  commonName: stevesloka.dev
  dnsNames:
  - stevesloka.dev
  issuerRef:
    name: letsencrypt-prod-dns
    kind: ClusterIssuer
  secretName: steveslokadev-tls