apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: containerstevecom-tls
spec:
  commonName: containersteve.com
  dnsNames:
  - containersteve.com
  - www.containersteve.com
  issuerRef:
    name: letsencrypt-prod-dns
    kind: ClusterIssuer
  secretName: containerstevecom-secret