apiVersion: apps/v1
kind: Deployment
metadata:
  name: rootapp3
  namespace: root-proxies
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rootapp3
  template:
    metadata:
      labels:
        app: rootapp3
    spec:
      containers:
      - name: echo
        image: stevesloka/echo-server
        command: ["echo-server"]
        args:
          - --echotext=This is the default app site [rootapp3]!
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rootapp3
  name: rootapp3
  namespace: root-proxies
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: rootapp3
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secureapp
  namespace: root-proxies
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secureapp
  template:
    metadata:
      labels:
        app: secureapp
    spec:
      containers:
      - name: echo
        image: stevesloka/echo-server
        command: ["echo-server"]
        args:
          - --echotext=This is the secure app site!
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: secureapp
  name: secureapp
  namespace: root-proxies
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: secureapp
  type: ClusterIP