apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: root
  namespace: root-proxies
spec:
  virtualhost:
    fqdn: demo.projectcontour.io
    tls:
      secretName: demoprojectcontourio-tls-wild
  routes:
  - services:
    - name: rootapp
      port: 80
    conditions:
      - prefix: /







  # includes:
  # - name: blogsite
  #   namespace: marketing
  #   conditions:
  #   - prefix: /blog
  #   - header:
  #       name: x-header
  #       exact: abc