apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: root-containersteve
  namespace: root-proxies
spec:
  virtualhost:
    fqdn: local.projectcontour.io
  includes:
  - name: blogsite
    namespace: marketing
    conditions:
    - prefix: /blog
    - header:
        name: User-Agent
        contains: Firefox
  routes:
  - services:
    - name: rootapp3
      port: 80
    conditions:
    - prefix: /









  # - services:
  #   - name: secureapp
  #     port: 80
  #   conditions:
  #     - prefix: /secure
  #     - header:
  #         name: User-Agent
  #         notcontains: Firefox
  #     - header:
  #         name: User-Agent
  #         notcontains: Chrome
    
    






  #         name: User-Agent
  #         notcontains: Chrome


  # includes:
  # - name: blogsite
  #   namespace: marketing
  #   conditions:
  #   - prefix: /blog
  #   - header:
  #       name: x-header
  #       exact: abc