apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  annotations:
  name: root
  namespace: projectcontour-roots
spec:
  virtualhost:
    fqdn: stevesloka.dev
    tls:
      secretName: steveslokadev-tls
    authorization:
      extensionRef:
        name: htpasswd
        namespace: projectcontour-auth
  includes:
  - name: blogsite
    namespace: projectcontour-marketing
    conditions:
    - prefix: /blog
  routes:
  - conditions:
    - prefix: /
    authPolicy:
      disabled: true
    services:
    - name: rootapp
      port: 80
  - conditions:
    - prefix: /secure
    services:
    - name: secureapp
      port: 80
