---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: auth
  name: authserver
  namespace: projectcontour-auth
spec:
  ports:
  - name: auth
    port: 10003
    protocol: TCP
    targetPort: 10003
  selector:
    app.kubernetes.io/name: auth
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: auth
  name: authserver
  namespace: projectcontour-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: auth
  template:
    metadata:
      labels:
        app.kubernetes.io/name: auth
    spec:
      containers:
      - image: stevesloka/istio-authservice:0.3.1-d3cd2d498169
        imagePullPolicy: IfNotPresent
        name: authservice
        ports:
        - containerPort: 10003
          name: auth
          protocol: TCP
        volumeMounts:
          - name: oidc-authservice-configmap-volume # mount the volume containing the authservice ConfigMap
            mountPath: /etc/authservice
      volumes:
        - name: oidc-authservice-configmap-volume # declare the volume containing the authservice ConfigMap
          configMap:
            name: oidc-authservice-configmap
