---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: blogsite
  namespace: marketing
spec:
  routes:
  - services:
    - name: wwwblog 
      port: 80
    conditions:
    - prefix: /  # /blog







#  includes:
#   - name: www
#     conditions:
#     - prefix: /info