apiVersion: v1
kind: ServiceAccount
metadata:
  name: projectcontour-auth-htpasswd
  namespace: root-proxies
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: projectcontour:authserver:htpasswd
  namespace: root-proxies
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: projectcontour:authserver:htpasswd
  namespace: root-proxies
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: projectcontour:authserver:htpasswd
subjects:
  - kind: ServiceAccount
    name: projectcontour-auth-htpasswd
    namespace: root-proxies
---
apiVersion: cert-manager.io/v1alpha3
kind: ClusterIssuer
metadata:
  name: selfsigned
spec:
  selfSigned: {}