---
apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: htpasswd
  namespace: root-proxies
spec:
  dnsNames:
  - htpasswd
  issuerRef:
    kind: ClusterIssuer
    name: selfsigned
  secretName: htpasswd
---
apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: ingress-conformance-echo
  namespace: root-proxies
spec:
  dnsNames:
  - local.projectcontour.io
  secretName: ingress-conformance-echo
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer