
# $ htpasswd -b auth user1 password1
# $ htpasswd -b auth user2 password2
# $ htpasswd -b auth user3 password3

---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: passwords
  namespace: projectcontour-auth
  annotations:
    projectcontour.io/auth-type: basic
data:
  auth: dXNlcjE6JGFwcjEkbEFFcGZZYW8kem1IZFdZa0dkVUVKSzkwbk9saTRCMQp1c2VyMjokYXByMSQ3R0Yuczg4VSQ2dEI4Y2FXWkROalZQTnVuMEQ2aVcwCnVzZXIzOiRhcHIxJEVSTWtmQmJnJE41MWQydll0VjBYZUVHWEpTLnBUTy4K

