apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: root
  namespace: marketing
spec:
  rules:
  - host: local.projectcontour.io
    http:
      paths:
      - path: /blog
        pathType: Prefix
        backend:
          service:
            name: wwwblog
            port:
              number: 80







              
      # - path: /secure
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: secureapp
      #       port:
      #         number: 80