apiVersion: cert-manager.io/v1alpha3
kind: ClusterIssuer
metadata:
  name: selfsigned
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: tlssecret
spec:
  dnsNames:
  - local.projectcontour.io
  secretName: tlssecret
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  labels:
    app: echocluster
  name: tcptest
spec:
  tcpproxy:
    # requestHeadersPolicy:
    #   set:
    #   - name: Host
    #     value: stevesloka.com
    services:
    - name: externalstevesloka
      port: 443
      protocol: tls
  virtualhost:
    fqdn: local.projectcontour.io
    tls:
      secretName: tlssecret
---
apiVersion: v1
kind: Service
metadata:
  name: externalstevesloka
spec:
  externalName: google.com
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  type: ExternalName