apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: root
spec:
  virtualhost:
    fqdn: stevesloka.com
    tls:
      secretName: containersteve-secret
  routes:
  - services:
    - name: ghost
      port: 2368
    conditions:
    - prefix: /