apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: root
  namespace: projectcontour-roots
spec:
  virtualhost:
    fqdn: local.projectcontour.io
  includes:
  - name: blogsite
    namespace: marketing
    conditions:
    - prefix: /blog
  routes:
  - services:
    - name: rootapp
      port: 80









    # includes:
    #   - name: blogsite
    #     namespace: marketing
    #     conditions:
    #     - prefix: /blog
    #     - header:
    #         name: User-Agent
    #         contains: Firefox


  # - services:
  #   - name: secureapp
  #     port: 80
  #   conditions:
  #     - prefix: /secure
  #     - header:
  #         name: User-Agent
  #         notcontains: Firefox
  #     - header:
  #         name: User-Agent
  #         notcontains: Chrome
    
  # authorization:
  #   extensionRef:
  #     name: htpasswd
  #     namespace: root-proxies





  #         name: User-Agent
  #         notcontains: Chrome


  # includes:
  # - name: blogsite
  #   namespace: marketing
  #   conditions:
  #   - prefix: /blog
  #   - header:
  #       name: x-header
  #       exact: abc