apiVersion: apps/v1
kind: Deployment
metadata:
  name: rootapp
  namespace:  bearcanoe-root
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rootapp
  template:
    metadata:
      labels:
        app: rootapp
    spec:
      containers:
      - name: echo
        image: stevesloka/echo-server:v0.2.0
        command: ["echo-server"]
        args:
          - --echotext=Welcome to Bear Canoe Industries [rootapp]!
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rootapp
  name: rootapp
  namespace: bearcanoe-root
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: rootapp
  type: ClusterIP