apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bearcanoe-tls
  namespace: bearcanoe-root
spec:
  commonName: bearcanoe.com
  dnsNames:
  - bearcanoe.com
  issuerRef:
    name: letsencrypt-prod-dns
    kind: ClusterIssuer
  secretName: bearcanoe-tls