---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: blogsite
  namespace: teama
spec:
  includes:
  - name: www
    namespace: teama
    conditions:
    - prefix: /info
  routes:
  - services:
    - name: wwwblog
      port: 80
    conditions:
      - prefix: /
