apiVersion: v1
kind: Service
metadata:
  labels:
    run: externaldns
  name: externaldns
  namespace: projectcontour-roots
spec:
  externalName: aa0352fd97dc011ea80d20a0582cb8bf-2ef76ca99935ad5c.elb.us-east-2.amazonaws.com
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  type: ExternalName